CREATE OR REPLACE VIEW HLIST
AS
SELECT ROWNUM RNUM, HEARTNO, JOBNO, USERNO
FROM (SELECT H.HEARTNO, H.JOBNO, J.USERNO
		FROM HEART H
		JOIN JOBSEARCH J ON(J.JOBNO = H.JOBNO)
		JOIN MEMBER M ON (M.USERNO = J.USERNO)
		WHERE J.TYPENO = 'J'
		ORDER BY 1 DESC);

		
CREATE OR REPLACE VIEW JLIST
AS
SELECT JOBNO,JOB,PERIOD,LOGOIMG,RECRUITMENT,GENDER,AGE,ADDRESS,PAY,DUEDATE,WORKTIME,WORKDAY,TITLE,CONTENT,JOBREPORT,WRITEDATE,COUNTRYNO,USERNO,CHANGENAME,COUNTRY,HEARTNO,JOBAPPLYNO,JOBAPPLYDATE			
FROM (SELECT J.JOBNO,J.JOB,J.PERIOD,J.LOGOIMG,J.RECRUITMENT,J.GENDER,J.AGE,J.ADDRESS,J.PAY,J.DUEDATE,J.WORKTIME,J.WORKDAY,J.TITLE,J.CONTENT,J.JOBREPORT,
J.WRITEDATE,J.COUNTRYNO,J.USERNO,J.CHANGENAME,C.COUNTRY,H.HEARTNO,JA.JOBAPPLYNO,JA.JOBAPPLYDATE
      FROM JOBSEARCH J
      JOIN HEART H ON (J.JOBNO = H.JOBNO)
      JOIN MEMBER M ON (M.USERNO = J.USERNO)
      JOIN COUNTRY C ON (J.COUNTRYNO = C.COUNTRYNO)
      JOIN JOBAPPLICATION JA ON JA.USERNO = J.USERNO AND JA.JOBNO = J.JOBNO
      JOIN LETTERTYPE L ON J.TYPENO = L.TYPENO
      WHERE J.TYPENO='J'
      ORDER BY 1 DESC);

CREATE OR REPLACE VIEW CLIST
AS
SELECT ROWNUM RNUM,COMMUNITYNO, TITLE, CONTENT,  WRITEDATE, VIEWCOUNT,REPORT,
			COUNTRYNO, CATEGORYNO,  USERNO, CATEGORYNAME
FROM (SELECT C.*,G.CATEGORYNAME
FROM COMMUNITY C
JOIN COMMUNITYCATEGORY G ON(G.CATEGORYNO = C.CATEGORYNO)
JOIN COUNTRY T ON (T.COUNTRYNO = C.COUNTRYNO)
JOIN LETTERTYPE L ON C.TYPENO = L.TYPENO
WHERE L.TYPENO='C')
;


CREATE OR REPLACE VIEW ALIST
AS
SELECT ROWNUM RNUM ,JOBNO,JOB,PERIOD,LOGOIMG,RECRUITMENT,GENDER,AGE,ADDRESS,PAY,DUEDATE,WORKTIME,WORKDAY,TITLE,CONTENT,JOBREPORT,WRITEDATE,COUNTRYNO,USERNO,CHANGENAME,COUNTRY,JOBAPPLYNO,JOBAPPLYDATE,USERNAME,EMAIL			
FROM (SELECT J.JOBNO,J.JOB,J.PERIOD,J.LOGOIMG,J.RECRUITMENT,J.GENDER,
    J.AGE,J.ADDRESS,J.PAY,J.DUEDATE,J.WORKTIME,J.WORKDAY,J.TITLE,
    J.CONTENT,J.JOBREPORT,J.WRITEDATE,J.COUNTRYNO,J.USERNO,J.CHANGENAME,C.COUNTRY,A.JOBAPPLYNO,A.JOBAPPLYDATE,M.USERNAME,M.EMAIL
      FROM JOBSEARCH J
      JOIN JOBAPPLICATION A ON (A.JOBNO = J.JOBNO) 
      JOIN MEMBER M ON (M.USERNO = A.USERNO)
      JOIN COUNTRY C ON (J.COUNTRYNO = C.COUNTRYNO)
      JOIN RESUME R ON (R.JOBAPPLYNO = A.JOBAPPLYNO)
      JOIN LETTERTYPE L ON J.TYPENO = L.TYPENO
      WHERE J.TYPENO='J'
      ORDER BY 1 DESC);

CREATE OR REPLACE VIEW HOMELIST
AS
SELECT ROWNUM RNUM ,USERNO,HOUSENO,TITLE,TYPE,PERIOD,FEE,ADDRESS,
     ESSENTIALITEM,WIFI,TELEVISION,HEATER,AIRCONDITIONAL,LIVINGROOM,BATHROOM,PET,RESERVATIONNO
FROM (SELECT H.USERNO,H.HOUSENO,H.TITLE,H.TYPE,H.PERIOD,H.FEE,H.ADDRESS,
     E.ESSENTIALITEM,E.WIFI,E.TELEVISION,E.HEATER,E.AIRCONDITIONAL,E.LIVINGROOM,E.BATHROOM,E.PET,HR.RESERVATIONNO
      FROM HOME H 
      JOIN HOMEETC E ON (E.HOUSENO = H.HOUSENO)
      JOIN MEMBER M ON (M.USERNO = H.USERNO)
      JOIN HOMERESERVATION HR ON (H.HOUSENO = HR.HOUSENO)
      JOIN LETTERTYPE L ON H.TYPENO = L.TYPENO
      WHERE L.TYPENO='H'
      );

     
 
CREATE OR REPLACE VIEW HRESERVATIONLIST
AS
SELECT ROWNUM RNUM ,TITLE,TYPE,PERIOD,RESERVATIONNO,USERNAME,EMAIL,R1,H1
FROM (SELECT H.TITLE,H.TYPE,H.PERIOD,HR.RESERVATIONNO,M.USERNAME,M.EMAIL,HR.USERNO AS R1 ,H.USERNO AS H1 
      FROM HOME H 
      JOIN HOMERESERVATION HR ON (HR.HOUSENO = H.HOUSENO)
      JOIN MEMBER M ON (HR.USERNO = M.USERNO)
      );        
      
CREATE OR REPLACE VIEW ARESERVATIONLIST
AS
SELECT ROWNUM RNUM ,PERIOD,TITLE,JOBAPPLYNO,USERNAME,EMAIL			
FROM (SELECT J.PERIOD,J.TITLE,A.JOBAPPLYNO,M.USERNAME,M.EMAIL
      FROM JOBSEARCH J
      JOIN JOBAPPLICATION A ON (A.JOBNO = J.JOBNO) 
      JOIN MEMBER M ON (M.USERNO = A.USERNO)
      ORDER BY 1 DESC);
CREATE OR REPLACE VIEW HRLIST
AS
SELECT USERNO,HOUSENO,TYPE,PERIOD,TITLE,FEE,ADDRESS,ESSENTIALITEM,WIFI,TELEVISION,HEATER,AIRCONDITIONAL,
       LIVINGROOM,BATHROOM,PET,USERNAME,EMAIL,RESERVATIONNO
FROM (SELECT USERNO,HOUSENO,TYPE,PERIOD,TITLE,FEE,ADDRESS,ESSENTIALITEM,WIFI,TELEVISION,HEATER,AIRCONDITIONAL,
       LIVINGROOM,BATHROOM,PET,USERNAME,EMAIL,RESERVATIONNO
      FROM HOME H 
      JOIN HOMERESERVATION HR ON (HR.HOUSENO = H.HOUSENO) AND (HR.USERNO = H.USERNO)
      JOIN HOMEETC HC ON (HC.HOUSENO = H.HOUSENO)
      JOIN MEMBER M ON (HR.USERNO = M.USERNO)
      ); 
      
       CREATE OR REPLACE VIEW JHLIST
AS
SELECT JOBNO,PERIOD,DUEDATE,WORKTIME,TITLE,COUNTRY,HEARTNO			
FROM (SELECT H.JOBNO,J.PERIOD,J.DUEDATE,J.WORKTIME,J.TITLE,C.COUNTRY,H.HEARTNO
      FROM JOBSEARCH J
      JOIN HEART H ON (J.JOBNO = H.JOBNO)
      JOIN MEMBER M ON (M.USERNO = H.USERNO)
      JOIN COUNTRY C ON (J.COUNTRYNO = C.COUNTRYNO)
      JOIN LETTERTYPE L ON J.TYPENO = L.TYPENO
      ORDER BY 1 DESC);